/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SPP_Sekolah;

/**
 *
 * @author user
 */
public class backup extends javax.swing.JFrame {

    /**
     * Creates new form backup
     */
    public backup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Pembayaran = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txt_idpembayaran = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        txt_cek_bayar_pmb = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel45 = new javax.swing.JLabel();
        txt_nisn_cek_pembayaran_pmb = new javax.swing.JTextField();
        btn_cek_bayar_pmb = new rojerusan.RSMaterialButtonRectangle();
        btn_search_cek_pembayaran_pmb = new javax.swing.JLabel();
        refresh_cek_bayar_pmb = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Table_cek_pmb = new javax.swing.JTable();
        jLabel46 = new javax.swing.JLabel();
        txt_nisn = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        txt_nama_siswa = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        txt_idkelas = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        txt_nama_siswa1 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel51 = new javax.swing.JLabel();
        choose_tgl_bayar_pmb = new com.toedter.calendar.JDateChooser();
        jLabel52 = new javax.swing.JLabel();
        choose_tgl_akhir_pmb = new com.toedter.calendar.JDateChooser();
        jLabel53 = new javax.swing.JLabel();
        choose_batas_pmb = new com.toedter.calendar.JDateChooser();
        jLabel54 = new javax.swing.JLabel();
        txt_id_spp = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        cbx_jumlah_bulan = new combobox.Combobox();
        jLabel56 = new javax.swing.JLabel();
        txt_nominal_bayar = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel57 = new javax.swing.JLabel();
        txt_uang_bayar = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel58 = new javax.swing.JLabel();
        txt_uang_kembalian = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        btn_bayar_pmb = new rojerusan.RSMaterialButtonRectangle();
        jLabel59 = new javax.swing.JLabel();
        txt_idpembayaran1 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Pembayaran.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("JetBrains Mono", 1, 40)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Pembayaran");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exchange-rate-biru.png"))); // NOI18N

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exchange-rate-biru.png"))); // NOI18N

        jLabel43.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel43.setText("ID PEMBAYARAN");

        txt_idpembayaran.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_idpembayaran.setToolTipText("Input Id Pembayaran");
        txt_idpembayaran.setBorder(null);
        txt_idpembayaran.setName(""); // NOI18N

        jLabel44.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel44.setText("Cari NISN dengan memasukan Namamu");

        txt_cek_bayar_pmb.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_cek_bayar_pmb.setToolTipText("Input Nama Untuk Pencarian");
        txt_cek_bayar_pmb.setBorder(null);
        txt_cek_bayar_pmb.setName(""); // NOI18N
        txt_cek_bayar_pmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cek_bayar_pmbActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel45.setText("Cek Pembayaran Menggunakan NISNmu");

        txt_nisn_cek_pembayaran_pmb.setEditable(false);
        txt_nisn_cek_pembayaran_pmb.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btn_cek_bayar_pmb.setBackground(new java.awt.Color(204, 204, 255));
        btn_cek_bayar_pmb.setForeground(new java.awt.Color(0, 0, 0));
        btn_cek_bayar_pmb.setText("Cek Pembayaran");
        btn_cek_bayar_pmb.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btn_cek_bayar_pmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cek_bayar_pmbActionPerformed(evt);
            }
        });

        btn_search_cek_pembayaran_pmb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-32px.png"))); // NOI18N
        btn_search_cek_pembayaran_pmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search_cek_pembayaran_pmbMouseClicked(evt);
            }
        });

        refresh_cek_bayar_pmb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh-ungu.png"))); // NOI18N
        refresh_cek_bayar_pmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refresh_cek_bayar_pmbMouseClicked(evt);
            }
        });

        Table_cek_pmb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Table_cek_pmb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_cek_pmb.setGridColor(new java.awt.Color(255, 255, 255));
        Table_cek_pmb.setIntercellSpacing(new java.awt.Dimension(5, 5));
        Table_cek_pmb.setRowHeight(25);
        Table_cek_pmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_cek_pmbMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(Table_cek_pmb);

        jLabel46.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Data Hasil Pencarian");

        txt_nisn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_nisn.setToolTipText("Input Id Pembayaran");
        txt_nisn.setBorder(null);
        txt_nisn.setName(""); // NOI18N

        jLabel47.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel47.setText("NISN");

        jLabel48.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel48.setText("Nama Siswa");

        txt_nama_siswa.setEditable(false);
        txt_nama_siswa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nama_siswa.setToolTipText("Input Nama Siswa");
        txt_nama_siswa.setBorder(null);
        txt_nama_siswa.setName(""); // NOI18N
        txt_nama_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_siswaActionPerformed(evt);
            }
        });

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        jLabel49.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel49.setText("ID KELAS");

        txt_idkelas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_idkelas.setToolTipText("Input Id Pembayaran");
        txt_idkelas.setBorder(null);
        txt_idkelas.setName(""); // NOI18N

        jLabel50.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel50.setText("Nama Kelas");

        txt_nama_siswa1.setEditable(false);
        txt_nama_siswa1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nama_siswa1.setToolTipText("Input Nama Siswa");
        txt_nama_siswa1.setBorder(null);
        txt_nama_siswa1.setName(""); // NOI18N
        txt_nama_siswa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_siswa1ActionPerformed(evt);
            }
        });

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));

        jLabel51.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel51.setText("Tanggal Bayar");

        choose_tgl_bayar_pmb.setToolTipText("Masukan Tanggal Pembayaran");

        jLabel52.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel52.setText("Tanggal Pembayaran Terakhir");

        choose_tgl_akhir_pmb.setToolTipText("Masukan Tanggal Pembayaran");

        jLabel53.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel53.setText("Batas Pembayaran SPP");

        choose_batas_pmb.setToolTipText("Masukan Tanggal Pembayaran");

        jLabel54.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel54.setText("ID SPP");

        txt_id_spp.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_id_spp.setToolTipText("Input Id Pembayaran");
        txt_id_spp.setBorder(null);
        txt_id_spp.setName(""); // NOI18N

        jLabel55.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel55.setText("Ingin Bayar Berapa Bulan");

        cbx_jumlah_bulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Bulan", "2 Bulan", "3 Bulan", "4 Bulan", "5 Bulan", "6 Bulan", "7 Bulan", "8 Bulan", "9 Bulan", "10 Bulan", "11 Bulan", "12 Bulan" }));
        cbx_jumlah_bulan.setSelectedIndex(-1);
        cbx_jumlah_bulan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbx_jumlah_bulan.setLabeText("Pilih Komp Keahlian");

        jLabel56.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel56.setText("Nominal Yang Harus Dibayar");

        txt_nominal_bayar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_nominal_bayar.setToolTipText("Input Id Pembayaran");
        txt_nominal_bayar.setBorder(null);
        txt_nominal_bayar.setName(""); // NOI18N

        jLabel57.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel57.setText("Uang Yang Dibayarkan");

        txt_uang_bayar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_uang_bayar.setToolTipText("Input Id Pembayaran");
        txt_uang_bayar.setBorder(null);
        txt_uang_bayar.setName(""); // NOI18N

        jLabel58.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel58.setText("Jumlah Uang Kembalian");

        txt_uang_kembalian.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_uang_kembalian.setToolTipText("Input Id Pembayaran");
        txt_uang_kembalian.setBorder(null);
        txt_uang_kembalian.setName(""); // NOI18N

        btn_bayar_pmb.setBackground(new java.awt.Color(204, 204, 255));
        btn_bayar_pmb.setForeground(new java.awt.Color(0, 0, 0));
        btn_bayar_pmb.setText("Bayar");
        btn_bayar_pmb.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btn_bayar_pmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayar_pmbActionPerformed(evt);
            }
        });

        jLabel59.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel59.setText("ID PEMBAYARAN");

        txt_idpembayaran1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_idpembayaran1.setToolTipText("Input Id Pembayaran");
        txt_idpembayaran1.setBorder(null);
        txt_idpembayaran1.setName(""); // NOI18N

        javax.swing.GroupLayout Panel_PembayaranLayout = new javax.swing.GroupLayout(Panel_Pembayaran);
        Panel_Pembayaran.setLayout(Panel_PembayaranLayout);
        Panel_PembayaranLayout.setHorizontalGroup(
            Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(choose_tgl_bayar_pmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_nisn, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                            .addComponent(jLabel49)
                            .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_idkelas, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)))
                        .addComponent(choose_batas_pmb, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41))
                    .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id_spp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_PembayaranLayout.createSequentialGroup()
                            .addComponent(jLabel54)
                            .addGap(276, 276, 276)))
                    .addComponent(jLabel43)
                    .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_idpembayaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel57)
                    .addComponent(txt_uang_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58)
                    .addComponent(txt_uang_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_bayar_pmb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)))
                .addGap(69, 69, 69)
                .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_jumlah_bulan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choose_tgl_akhir_pmb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nama_siswa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(txt_idpembayaran1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nama_siswa1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nominal_bayar))
                .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_nisn_cek_pembayaran_pmb, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_cek_bayar_pmb, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PembayaranLayout.createSequentialGroup()
                            .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel44)
                                .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                                    .addComponent(txt_cek_bayar_pmb, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_search_cek_pembayaran_pmb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(refresh_cek_bayar_pmb)))
                            .addGap(107, 107, 107))
                        .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PembayaranLayout.createSequentialGroup()
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_PembayaranLayout.setVerticalGroup(
            Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                        .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel41)
                                .addComponent(jLabel17)))
                        .addGap(158, 158, 158)
                        .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                                .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addGap(2, 2, 2)
                                        .addComponent(txt_idpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel47)
                                        .addGap(2, 2, 2)
                                        .addComponent(txt_nisn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel49)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_idkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                                        .addComponent(jLabel59)
                                        .addGap(2, 2, 2)
                                        .addComponent(txt_idpembayaran1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel48)
                                        .addGap(1, 1, 1)
                                        .addComponent(txt_nama_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel50)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_nama_siswa1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                                        .addComponent(jLabel51)
                                        .addGap(9, 9, 9)
                                        .addComponent(choose_tgl_bayar_pmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                                        .addComponent(jLabel52)
                                        .addGap(9, 9, 9)
                                        .addComponent(choose_tgl_akhir_pmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel53)
                                    .addComponent(jLabel55))
                                .addGap(9, 9, 9)
                                .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choose_batas_pmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbx_jumlah_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                                        .addComponent(jLabel54)
                                        .addGap(8, 8, 8)
                                        .addComponent(txt_id_spp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                                        .addComponent(jLabel56)
                                        .addGap(8, 8, 8)
                                        .addComponent(txt_nominal_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel57)
                                .addGap(8, 8, 8)
                                .addComponent(txt_uang_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_bayar_pmb, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(jLabel58)
                                .addGap(8, 8, 8)
                                .addComponent(txt_uang_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                        .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_PembayaranLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(Panel_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_cek_bayar_pmb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_search_cek_pembayaran_pmb)
                                    .addComponent(refresh_cek_bayar_pmb))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nisn_cek_pembayaran_pmb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(btn_cek_bayar_pmb, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jLabel46)
                        .addGap(730, 730, 730))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Panel_Pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Panel_Pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cek_bayar_pmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cek_bayar_pmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cek_bayar_pmbActionPerformed

    private void btn_cek_bayar_pmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cek_bayar_pmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cek_bayar_pmbActionPerformed

    private void btn_search_cek_pembayaran_pmbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_cek_pembayaran_pmbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_search_cek_pembayaran_pmbMouseClicked

    private void refresh_cek_bayar_pmbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_cek_bayar_pmbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_refresh_cek_bayar_pmbMouseClicked

    private void Table_cek_pmbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_cek_pmbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Table_cek_pmbMouseClicked

    private void txt_nama_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_siswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_siswaActionPerformed

    private void txt_nama_siswa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_siswa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_siswa1ActionPerformed

    private void btn_bayar_pmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayar_pmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bayar_pmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new backup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Pembayaran;
    private javax.swing.JTable Table_cek_pmb;
    private rojerusan.RSMaterialButtonRectangle btn_bayar_pmb;
    private rojerusan.RSMaterialButtonRectangle btn_cek_bayar_pmb;
    private javax.swing.JLabel btn_search_cek_pembayaran_pmb;
    private combobox.Combobox cbx_jumlah_bulan;
    private com.toedter.calendar.JDateChooser choose_batas_pmb;
    private com.toedter.calendar.JDateChooser choose_tgl_akhir_pmb;
    private com.toedter.calendar.JDateChooser choose_tgl_bayar_pmb;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel refresh_cek_bayar_pmb;
    private javax.swing.JTextField txt_cek_bayar_pmb;
    private javax.swing.JTextField txt_id_spp;
    private javax.swing.JTextField txt_idkelas;
    private javax.swing.JTextField txt_idpembayaran;
    private javax.swing.JTextField txt_idpembayaran1;
    private javax.swing.JTextField txt_nama_siswa;
    private javax.swing.JTextField txt_nama_siswa1;
    private javax.swing.JTextField txt_nisn;
    private javax.swing.JTextField txt_nisn_cek_pembayaran_pmb;
    private javax.swing.JTextField txt_nominal_bayar;
    private javax.swing.JTextField txt_uang_bayar;
    private javax.swing.JTextField txt_uang_kembalian;
    // End of variables declaration//GEN-END:variables
}
