/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SPP_Sekolah;

import java.awt.Color;
import java.awt.Panel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;
import notification.Notification;

/**
 *
 * @author user
 */
public class Form_Pembayaran extends javax.swing.JInternalFrame {

    DefaultTableModel tabmode;

        String date_format;
    public Form_Pembayaran() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).setNorthPane(null);
        Object[] row = {"Id Pembayaran", "Id Petugas", "Nama Petugas", "Nisn", "Nama Siswa", "Tanggal Bayar", "Id SPP", "Nominal", "Jumlah Bayar"};
        tabmode = new DefaultTableModel(null, row);
        Table.setModel(tabmode);
        jPanel8.setBackground(new Color(0, 0, 0, 30));
        tampilkandata();
        model_cbx_idpetugas();
        model_cbx_nisn();
        model_cbx_idspp();
    }

    public void tampilkandata() {
        try {
            Connection conn = (Connection) koneksi.koneksiDB();
            String sql = "Select tb_pembayaran.*, tb_petugas.id_petugas,nama_petugas , tb_siswa.nisn,nama , tb_spp.id_spp,nominal from tb_pembayaran join tb_petugas on tb_petugas.id_petugas = tb_pembayaran.id_petugas"
                    + " join tb_siswa on tb_siswa.nisn = tb_pembayaran.nisn join tb_spp on tb_spp.id_spp = tb_pembayaran.id_spp";
            Statement stat = conn.createStatement();
            ResultSet set = stat.executeQuery(sql);
            while (set.next()) {
                String[] data = {set.getString("id_pembayaran"),
                    set.getString("id_petugas"),
                    set.getString("nama_petugas"),
                    set.getString("nisn"),
                    set.getString("nama"),
                    set.getString("tgl_bayar"),
                    set.getString("id_spp"),
                    set.getString("nominal"),
                    set.getString("jumlah_bayar")};

                tabmode.addRow(data);
            }

        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Tampilkan Data"+ e);
            panel.showNotification();
        }
    }

    public void resetText() {
        hapustabel();
        txt_idpembayaran.setText("");
        txt_search.setText("");
        cbx_idpetugas.setSelectedIndex(-1);
        cbx_nisn.setSelectedIndex(-1);
        cbx_idspp.setSelectedIndex(-1);
        txt_jmlah_bayar.setText("");
        txt_nominal.setText("");
        txt_nama_siswa.setText("");
        txt_nama_petugas.setText("");
        txt_idpembayaran.setEditable(true);
        choose_date.setDate(null);
        tampilkandata();
    }

    public void hapustabel() {
        int row = tabmode.getRowCount();
        for (int i = 0; i < row; i++) {
            tabmode.removeRow(0);
        }
    }
    
    public void format_date(){
        String pattern = "yyyy-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(pattern);
        date_format = String.valueOf(format.format(choose_date.getDate()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idpembayaran = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txt_jmlah_bayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nama_petugas = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txt_nominal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        choose_date = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txt_nama_siswa = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        cbx_idpetugas = new combobox.Combobox();
        cbx_nisn = new combobox.Combobox();
        cbx_idspp = new combobox.Combobox();
        btn_save = new rojerusan.RSMaterialButtonRectangle();
        btn_delete = new rojerusan.RSMaterialButtonRectangle();
        btn_edit = new rojerusan.RSMaterialButtonRectangle();
        btn_refresh = new rojerusan.RSMaterialButtonRectangle();
        btn_back = new rojerusan.RSMaterialButtonRectangle();
        jPanel5 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btn_search = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(16, 181, 232));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Pembayaran");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel2.setText("ID PEMBAYARAN");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel5.setText("Input Data");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel4.setText("ID SPP");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel3.setText("ID PETUGAS");

        txt_idpembayaran.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_idpembayaran.setToolTipText("Input Id Pembayaran");
        txt_idpembayaran.setBorder(null);
        txt_idpembayaran.setName(""); // NOI18N

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel6.setText("NISN");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel7.setText("TANGGAL BAYAR");

        txt_jmlah_bayar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_jmlah_bayar.setToolTipText("Input Jumlah Bayar");
        txt_jmlah_bayar.setBorder(null);
        txt_jmlah_bayar.setName(""); // NOI18N
        txt_jmlah_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jmlah_bayarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel8.setText("JUMLAH BAYAR");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel10.setText("Nama Petugas");

        txt_nama_petugas.setEditable(false);
        txt_nama_petugas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_nama_petugas.setToolTipText("Input Nama Petugas");
        txt_nama_petugas.setBorder(null);
        txt_nama_petugas.setName(""); // NOI18N
        txt_nama_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_petugasActionPerformed(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        txt_nominal.setEditable(false);
        txt_nominal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nominal.setToolTipText("Input Nominal");
        txt_nominal.setBorder(null);
        txt_nominal.setName(""); // NOI18N
        txt_nominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nominalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel11.setText("Nominal");

        choose_date.setToolTipText("Masukan Tanggal Pembayaran");

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel12.setText("Nama Siswa");

        txt_nama_siswa.setEditable(false);
        txt_nama_siswa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nama_siswa.setToolTipText("Input Nama Siswa");
        txt_nama_siswa.setBorder(null);
        txt_nama_siswa.setName(""); // NOI18N
        txt_nama_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_siswaActionPerformed(evt);
            }
        });

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));

        cbx_idpetugas.setToolTipText("");
        cbx_idpetugas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbx_idpetugas.setLabeText("Masukan Id Petugas");
        cbx_idpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_idpetugasActionPerformed(evt);
            }
        });

        cbx_nisn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbx_nisn.setLabeText("Masukan NISN");
        cbx_nisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_nisnActionPerformed(evt);
            }
        });

        cbx_idspp.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbx_idspp.setLabeText("Masukan Id SPP");
        cbx_idspp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_idsppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator6)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(123, 123, 123)
                                            .addComponent(jSeparator5))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(219, 219, 219)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txt_jmlah_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbx_idpetugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7))
                                                .addComponent(cbx_nisn, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbx_idspp, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4))
                                            .addGap(28, 28, 28)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel10)
                                                    .addComponent(txt_nama_siswa, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                                    .addComponent(jSeparator9)
                                                    .addComponent(txt_nominal))
                                                .addComponent(txt_nama_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(choose_date, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 11, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txt_idpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(txt_idpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cbx_idpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txt_nama_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cbx_nisn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txt_nama_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(choose_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cbx_idspp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txt_nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_jmlah_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 108, Short.MAX_VALUE))
        );

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(153, 204, 255));
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_search.setBorder(null);
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jScrollPane2.setBorder(null);

        Table.setAutoCreateRowSorter(true);
        Table.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Pembayaran", "Id Petugas", "Nama Petugas", "NISN", "Nama Siswa", "Tanggal Bayar", "Id Spp", "Nominal", "Jumlah Bayar"
            }
        ));
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        Table.setIntercellSpacing(new java.awt.Dimension(5, 5));
        Table.setRowHeight(25);
        Table.setSelectionBackground(new java.awt.Color(16, 181, 232));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(1).setResizable(false);
            Table.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/loupe.png"))); // NOI18N
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1326, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 924, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        delete_data();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        editdata();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        resetText();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        table_mouse_klik();
    }//GEN-LAST:event_TableMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        // TODO add your handling code here:
        search_data();
    }//GEN-LAST:event_btn_searchMouseClicked

    private void txt_nominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nominalActionPerformed

    private void txt_nama_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_petugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_petugasActionPerformed

    private void txt_jmlah_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jmlah_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jmlah_bayarActionPerformed

    private void txt_nama_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_siswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_siswaActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        hapustabel();
        String key = txt_search.getText();
        try {
            String sql = "Select tb_pembayaran.*, tb_petugas.id_petugas,nama_petugas , tb_siswa.nisn,nama , tb_spp.id_spp,nominal from tb_pembayaran join tb_petugas on tb_petugas.id_petugas = tb_pembayaran.id_petugas"
                    + " join tb_siswa on tb_siswa.nisn = tb_pembayaran.nisn join tb_spp on tb_spp.id_spp = tb_pembayaran.id_spp"
                    + " WHERE id_pembayaran LIKE '%" + key + "%' OR tb_siswa.nama LIKE '%" + key + "%' OR tb_petugas.nama_petugas LIKE '" + key + "'";
            Connection conn = (Connection)koneksi.koneksiDB();
            Statement stat = conn.createStatement();
            ResultSet set = stat.executeQuery(sql);
            while (set.next()){
                String[] data = {set.getString("id_pembayaran"),
                    set.getString("id_petugas"),
                    set.getString("nama_petugas"),
                    set.getString("nisn"),
                    set.getString("nama"),
                    set.getString("tgl_bayar"),
                    set.getString("id_spp"),
                    set.getString("nominal"),
                    set.getString("jumlah_bayar")};
                tabmode.addRow(data);
            }
            
        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Search Key Release Data"+ e);
            panel.showNotification();
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void cbx_idpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_idpetugasActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "Select nama_petugas from tb_petugas where id_petugas ='"+cbx_idpetugas.getSelectedItem()+"'";
        Connection conn = (Connection)koneksi.koneksiDB();
        Statement stat = conn.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        if(rs.next()){
            txt_nama_petugas.setText(rs.getString("nama_petugas"));
        }
        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Cbx Id Petugas"+ e);
            panel.showNotification();
        }
    }//GEN-LAST:event_cbx_idpetugasActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        this.requestFocusInWindow(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void cbx_nisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_nisnActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "Select nama from tb_siswa where nisn ='"+cbx_nisn.getSelectedItem()+"'";
        Connection conn = (Connection)koneksi.koneksiDB();
        Statement stat = conn.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        if(rs.next()){
            txt_nama_siswa.setText(rs.getString("nama"));
        }
        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Cbx Nisn"+ e);
            panel.showNotification();
        }
    }//GEN-LAST:event_cbx_nisnActionPerformed

    private void cbx_idsppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_idsppActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "Select nominal from tb_spp where id_spp ='"+cbx_idspp.getSelectedItem()+"'";
        Connection conn = (Connection)koneksi.koneksiDB();
        Statement stat = conn.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        if(rs.next()){
            txt_nominal.setText(rs.getString("nominal"));
        }
        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Cbx Id Petugas"+ e);
            panel.showNotification();
        }
    }//GEN-LAST:event_cbx_idsppActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        this.requestFocusInWindow(true);
    }//GEN-LAST:event_jPanel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private rojerusan.RSMaterialButtonRectangle btn_back;
    private rojerusan.RSMaterialButtonRectangle btn_delete;
    private rojerusan.RSMaterialButtonRectangle btn_edit;
    private rojerusan.RSMaterialButtonRectangle btn_refresh;
    private rojerusan.RSMaterialButtonRectangle btn_save;
    private javax.swing.JLabel btn_search;
    private combobox.Combobox cbx_idpetugas;
    private combobox.Combobox cbx_idspp;
    private combobox.Combobox cbx_nisn;
    private com.toedter.calendar.JDateChooser choose_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txt_idpembayaran;
    private javax.swing.JTextField txt_jmlah_bayar;
    private javax.swing.JTextField txt_nama_petugas;
    private javax.swing.JTextField txt_nama_siswa;
    private javax.swing.JTextField txt_nominal;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

    private void save() {
        hapustabel();
        format_date();
        try {
            String sql = "Insert into tb_pembayaran values('" + txt_idpembayaran.getText()
                    + "','" + cbx_idpetugas.getSelectedItem()
                    + "','" + cbx_nisn.getSelectedItem()
                    + "','" + date_format
                    + "','" + cbx_idspp.getSelectedItem()
                    + "','" + txt_jmlah_bayar.getText()+ "');";
            Connection conn = (Connection) koneksi.koneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            Notification panel = new Notification(null, Notification.Type.SUCCESS, Notification.Location.CENTER_RIGHT,
                    "Save Succesfull");
            panel.showNotification();
        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT, "Ada Kesalahan Di Save Data"+ e);
            panel.showNotification();
        }
        tampilkandata();
        resetText();
    }

    private void editdata() {
        hapustabel();
        format_date();
        try {
            String sql = "update tb_pembayaran set id_petugas='" + cbx_idpetugas.getSelectedItem()
                    + "',nisn='" + cbx_nisn.getSelectedItem()
                    + "',tgl_bayar='" + date_format
                    + "',id_spp='" + cbx_idspp.getSelectedItem()
                    + "',jumlah_bayar='" + txt_jmlah_bayar.getText()
                    + "' WHERE id_pembayaran='" + txt_idpembayaran.getText() + "'";

            Connection conn = (Connection) koneksi.koneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            Notification panel = new Notification(null, Notification.Type.SUCCESS, Notification.Location.CENTER_RIGHT, "Edit Succesfull");
            panel.showNotification();
        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT, "Ada Kesalahan Di Edit Data"+ e);
            panel.showNotification();
        }
        tampilkandata();
        resetText();
    }

    public void delete_data() {
        hapustabel();
        try {
            String sql = "DELETE FROM tb_pembayaran WHERE id_pembayaran = '" + txt_idpembayaran.getText() + "'";

            Connection conn = (Connection) koneksi.koneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            Notification panel = new Notification(null, Notification.Type.SUCCESS, Notification.Location.CENTER_RIGHT, "Delete Succesfull");
            panel.showNotification();
        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT, "Ada Kesalahan Di Delete Data"+ e);
            panel.showNotification();
        }
        tampilkandata();
        resetText();

    }

    public void search_data() {
        hapustabel();
        String key = txt_search.getText();
        try {
            Connection conn = (Connection) koneksi.koneksiDB();
            String sql = "Select tb_pembayaran.*, tb_petugas.id_petugas,nama_petugas , tb_siswa.nisn,nama , tb_spp.id_spp,nominal from tb_pembayaran join tb_petugas on tb_petugas.id_petugas = tb_pembayaran.id_petugas"
                    + " join tb_siswa on tb_siswa.nisn = tb_pembayaran.nisn join tb_spp on tb_spp.id_spp = tb_pembayaran.id_spp"
                    + " WHERE id_pembayaran LIKE '%" + key + "%' OR tb_siswa.nama LIKE '%" + key + "%' OR tb_petugas.nama_petugas LIKE '" + key + "'";
            Statement stat = conn.createStatement();
            ResultSet set = stat.executeQuery(sql);
            while (set.next()) {
                String[] data = {set.getString("id_pembayaran"),
                    set.getString("id_petugas"),
                    set.getString("nama_petugas"),
                    set.getString("nisn"),
                    set.getString("nama"),
                    set.getString("tgl_bayar"),
                    set.getString("id_spp"),
                    set.getString("nominal"),
                    set.getString("jumlah_bayar")};
                tabmode.addRow(data);
            }

        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT, "Ada Kesalahan Di Search Data"+ e);
            panel.showNotification();
        }
    }

    public void table_mouse_klik() {
        try {
            txt_idpembayaran.setEditable(false);
            int row = Table.getSelectedRow();
            String table_klik = (Table.getModel().getValueAt(row, 0).toString());
            java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
            Statement stm = conn.createStatement();
            ResultSet sql = stm.executeQuery("Select tb_pembayaran.*, tb_petugas.id_petugas,nama_petugas , tb_siswa.nisn,nama , tb_spp.id_spp,nominal from tb_pembayaran join tb_petugas on tb_petugas.id_petugas = tb_pembayaran.id_petugas"
                                           + " join tb_siswa on tb_siswa.nisn = tb_pembayaran.nisn join tb_spp on tb_spp.id_spp = tb_pembayaran.id_spp where id_pembayaran='" + table_klik + "'");
            if (sql.next()) {
                String add1 = sql.getString("id_pembayaran");
                txt_idpembayaran.setText(add1);
                String add2 = sql.getString("id_petugas");
                cbx_idpetugas.setSelectedItem(add2);
                String add3 = sql.getString("nama_petugas");
                txt_nama_petugas.setText(add3);
                String add4 = sql.getString("nisn");
                cbx_nisn.setSelectedItem(add4);
                String add5 = sql.getString("nama");
                txt_nama_siswa.setText(add5);
                Date add6 = sql.getDate("tgl_bayar");
                choose_date.setDate(add6);
                String add7 = sql.getString("id_spp");
                cbx_idspp.setSelectedItem(add7);
                String add8 = sql.getString("nominal");
                txt_nominal.setText(add8);
                String add9 = sql.getString("jumlah_bayar");
                txt_jmlah_bayar.setText(add9);
                
            }
        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT, "Ada Kesalahan Di Mouse Click"+ e);
            panel.showNotification();
        }
    }
    
    public void model_cbx_idpetugas(){
        try {
        Connection conn = (Connection)koneksi.koneksiDB();
        String sql = "Select id_petugas from tb_petugas";
        Statement stat = conn.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        while (rs.next()){
            cbx_idpetugas.addItem(rs.getString("id_petugas"));
        }
        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT, "Ada Kesalahan Di Cbx Id Kelas"+ e);
            panel.showNotification();
        }
        cbx_idpetugas.setSelectedIndex(-1);
        txt_nama_petugas.setText("");
    }
    
    public void model_cbx_nisn(){
        try {
        Connection conn = (Connection)koneksi.koneksiDB();
        String sql = "Select nisn from tb_siswa";
        Statement stat = conn.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        while (rs.next()){
            cbx_nisn.addItem(rs.getString("nisn"));
        }
        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT, "Ada Kesalahan Di Cbx Nisn"+ e);
            panel.showNotification();
        }
        cbx_nisn.setSelectedIndex(-1);
        txt_nama_siswa.setText("");
    }
    
    public void model_cbx_idspp(){
        try {
        Connection conn = (Connection)koneksi.koneksiDB();
        String sql = "Select id_spp from tb_spp";
        Statement stat = conn.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        while (rs.next()){
            cbx_idspp.addItem(rs.getString("id_spp"));
        }
        } catch (Exception e) {
            Notification panel = new Notification(null, Notification.Type.WARNING, Notification.Location.CENTER_RIGHT, "Ada Kesalahan Di Cbx Id SPP"+ e);
            panel.showNotification();
        }
        cbx_idspp.setSelectedIndex(-1);
        txt_nominal.setText("");
    }

}
