/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_lama;

import SPP_Sekolah.Form_Menu_Admin;
import SPP_Sekolah.koneksi;
import java.awt.Color;
import java.awt.Panel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;
import javax.swing.table.TableColumn;
import notification.Notification;

/**
 *
 * @author user
 */
public class Form_Siswa extends javax.swing.JInternalFrame {

    DefaultTableModel tabmode;

    public Form_Siswa() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).setNorthPane(null);
        Object[] row = {"NISN", "NIS", "Nama", "Id Kelas", "Komp Keahlian", "Alamat", "No Telpon", "Id SPP", "Nominal"};
        tabmode = new DefaultTableModel(null, row);
        Table.setModel(tabmode);
        jPanel8.setBackground(new Color(0, 0, 0, 30));
        tampilkandata();
        model_cbx_idkelas();
        model_cbx_idspp();
        table_model();
    }

    public void tampilkandata() {
        try {
            Connection conn = (Connection) koneksi.koneksiDB();
            String sql = "Select tb_siswa.*, tb_kelas.id_kelas,komp_keahlian , tb_spp.id_spp,nominal from tb_siswa join tb_kelas on tb_kelas.id_kelas = tb_siswa.id_kelas join tb_spp on tb_spp.id_spp = tb_siswa.id_spp";
            Statement stat = conn.createStatement();
            ResultSet set = stat.executeQuery(sql);
            while (set.next()) {
                String[] data = {set.getString("nisn"),
                    set.getString("nis"),
                    set.getString("nama"),
                    set.getString("id_kelas"),
                    set.getString("komp_keahlian"),
                    set.getString("alamat"),
                    set.getString("no_telp"),
                    set.getString("id_spp"),
                    set.getString("nominal")};

                tabmode.addRow(data);
            }

        } catch (Exception e) {
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Tampilkan Data"+ e);
            panel.showNotification();
        }
    }

    public void resetText() {
        hapustabel();
        txt_nisn.setText("");
        txt_nis.setText("");
        txt_nama.setText("");
        txt_search.setText("");
        txt_alamat.setText("");
        cbx_idkelas.setSelectedIndex(-1);
        cbx_idspp.setSelectedIndex(-1);
        txt_notelp.setText("");
        txt_nominal.setText("");
        txt_komp_keahlian.setText("");
        txt_nisn.setEditable(true);
        tampilkandata();
    }

    public void hapustabel() {
        int row = tabmode.getRowCount();
        for (int i = 0; i < row; i++) {
            tabmode.removeRow(0);
        }
    }
    
    public void table_model(){
        TableColumn column;
        Table.getColumnModel().getColumn(0).setPreferredWidth(40);
        Table.getColumnModel().getColumn(1).setPreferredWidth(40);
        Table.getColumnModel().getColumn(3).setPreferredWidth(40);
        Table.getColumnModel().getColumn(4).setPreferredWidth(100);
        Table.getColumnModel().getColumn(5).setPreferredWidth(150);
        Table.getColumnModel().getColumn(6).setPreferredWidth(90);
        Table.getColumnModel().getColumn(7).setPreferredWidth(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nisn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_nama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txt_notelp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_komp_keahlian = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txt_nominal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        cbx_idkelas = new combobox.Combobox();
        cbx_idspp = new combobox.Combobox();
        btn_save = new rojerusan.RSMaterialButtonRectangle();
        btn_delete = new rojerusan.RSMaterialButtonRectangle();
        btn_edit = new rojerusan.RSMaterialButtonRectangle();
        btn_refresh = new rojerusan.RSMaterialButtonRectangle();
        btn_back = new rojerusan.RSMaterialButtonRectangle();
        jPanel5 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btn_search = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(16, 181, 232));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Siswa");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel2.setText("NISN");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel5.setText("Input Data");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel4.setText("ALAMAT");

        txt_nis.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_nis.setToolTipText("Input NIS");
        txt_nis.setBorder(null);
        txt_nis.setName(""); // NOI18N
        txt_nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nisActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel3.setText("NIS");

        txt_nisn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_nisn.setToolTipText("Input NISN");
        txt_nisn.setBorder(null);
        txt_nisn.setName(""); // NOI18N

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        txt_nama.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_nama.setToolTipText("Input Nama");
        txt_nama.setBorder(null);
        txt_nama.setName(""); // NOI18N
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel6.setText("NAMA");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel7.setText("ID KELAS");

        txt_alamat.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_alamat.setToolTipText("Input Alamat");
        txt_alamat.setBorder(null);
        txt_alamat.setName(""); // NOI18N
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        txt_notelp.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_notelp.setToolTipText("Input No Telpon");
        txt_notelp.setBorder(null);
        txt_notelp.setName(""); // NOI18N
        txt_notelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_notelpActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel8.setText("NO TELPON");

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel9.setText("ID SPP");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel10.setText("Komp Keahlian");

        txt_komp_keahlian.setEditable(false);
        txt_komp_keahlian.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_komp_keahlian.setToolTipText("Input Komp Keahlian");
        txt_komp_keahlian.setBorder(null);
        txt_komp_keahlian.setName(""); // NOI18N
        txt_komp_keahlian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_komp_keahlianActionPerformed(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        txt_nominal.setEditable(false);
        txt_nominal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nominal.setToolTipText("Input Nominal");
        txt_nominal.setBorder(null);
        txt_nominal.setName(""); // NOI18N
        txt_nominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nominalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel11.setText("Nominal");

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        cbx_idkelas.setToolTipText("");
        cbx_idkelas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbx_idkelas.setLabeText("Masukan Id Kelas");
        cbx_idkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_idkelasActionPerformed(evt);
            }
        });

        cbx_idspp.setToolTipText("");
        cbx_idspp.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbx_idspp.setLabeText("Masukan Id Kelas");
        cbx_idspp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_idsppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txt_nisn, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5)))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator6)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nis, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(cbx_idspp, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addComponent(txt_nominal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(cbx_idkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_komp_keahlian))))))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(txt_nisn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(txt_nis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cbx_idkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txt_komp_keahlian, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_idspp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(153, 204, 255));
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_search.setBorder(null);
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jScrollPane2.setBorder(null);

        Table.setAutoCreateRowSorter(true);
        Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Table.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nisn", "Nis", "Nama", "Id Kelas", "Komp Keahlian", "Alamat", "No Telp", "Id Spp"
            }
        ));
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        Table.setIntercellSpacing(new java.awt.Dimension(5, 5));
        Table.setRowHeight(25);
        Table.setSelectionBackground(new java.awt.Color(16, 181, 232));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/loupe.png"))); // NOI18N
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nisActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        delete_data();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        editdata();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        resetText();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        table_mouse_klik();
    }//GEN-LAST:event_TableMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        // TODO add your handling code here:
        search_data();
    }//GEN-LAST:event_btn_searchMouseClicked

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_notelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_notelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_notelpActionPerformed

    private void txt_komp_keahlianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_komp_keahlianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_komp_keahlianActionPerformed

    private void txt_nominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nominalActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        hapustabel();
        String key = txt_search.getText();
        try {
            Connection conn = (Connection) koneksi.koneksiDB();
            String sql = "Select tb_siswa.*, tb_kelas.id_kelas,komp_keahlian , tb_spp.id_spp,nominal from tb_siswa join tb_kelas "
                    + "on tb_kelas.id_kelas = tb_siswa.id_kelas join tb_spp on tb_spp.id_spp = tb_siswa.id_spp WHERE nama "
                    + "LIKE '%" + key + "%' OR nisn LIKE '%" + key + "%' OR komp_keahlian LIKE '%"+ key +"%' OR alamat LIKE '%"+ key +"%'";
            Statement stat = conn.createStatement();
            ResultSet set = stat.executeQuery(sql);
            while (set.next()) {
                String[] data = {set.getString("nisn"),
                    set.getString("nis"),
                    set.getString("nama"),
                    set.getString("id_kelas"),
                    set.getString("komp_keahlian"),
                    set.getString("alamat"),
                    set.getString("no_telp"),
                    set.getString("id_spp"),
                    set.getString("nominal")};
                tabmode.addRow(data);
            }
            
        } catch (Exception e) {
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Search Key Release"+ e);
            panel.showNotification();
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void cbx_idkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_idkelasActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Select komp_keahlian from tb_kelas where id_kelas ='"+cbx_idkelas.getSelectedItem()+"'";
            Connection conn = (Connection)koneksi.koneksiDB();
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if(rs.next()){
                txt_komp_keahlian.setText(rs.getString("komp_keahlian"));
            }
        } catch (Exception e) {
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                "Ada Kesalahan Di Cbx Id kelas"+ e);
            panel.showNotification();
        }
    }//GEN-LAST:event_cbx_idkelasActionPerformed

    private void cbx_idsppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_idsppActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Select nominal from tb_spp where id_spp ='"+cbx_idspp.getSelectedItem()+"'";
            Connection conn = (Connection)koneksi.koneksiDB();
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if(rs.next()){
                txt_nominal.setText(rs.getString("nominal"));
            }
        } catch (Exception e) {
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                "Ada Kesalahan Di Cbx Id SPP"+ e);
            panel.showNotification();
        }
    }//GEN-LAST:event_cbx_idsppActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        this.requestFocusInWindow(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.requestFocusInWindow(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        this.requestFocusInWindow(true);
    }//GEN-LAST:event_jPanel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private rojerusan.RSMaterialButtonRectangle btn_back;
    private rojerusan.RSMaterialButtonRectangle btn_delete;
    private rojerusan.RSMaterialButtonRectangle btn_edit;
    private rojerusan.RSMaterialButtonRectangle btn_refresh;
    private rojerusan.RSMaterialButtonRectangle btn_save;
    private javax.swing.JLabel btn_search;
    private combobox.Combobox cbx_idkelas;
    private combobox.Combobox cbx_idspp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_komp_keahlian;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nis;
    private javax.swing.JTextField txt_nisn;
    private javax.swing.JTextField txt_nominal;
    private javax.swing.JTextField txt_notelp;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

    private void save() {
        hapustabel();
        try {
            String sql = "Insert into tb_siswa values('" + txt_nisn.getText()
                    + "','" + txt_nis.getText()
                    + "','" + txt_nama.getText()
                    + "','" + cbx_idkelas.getSelectedItem()
                    + "','" + txt_alamat.getText()
                    + "','" + txt_notelp.getText()
                    + "','" + cbx_idspp.getSelectedItem() + "');";
            Connection conn = (Connection) koneksi.koneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.SUCCESS, Notification.Location.CENTER_RIGHT,
                    "Save Succesfull");
            panel.showNotification();
        } catch (Exception e) {
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Save Data"+ e);
            panel.showNotification();
        }
        tampilkandata();
        resetText();
    }

    private void editdata() {
        hapustabel();
        try {
            String sql = "update tb_siswa set nis='" + txt_nis.getText()
                    + "',nama='" + txt_nama.getText()
                    + "',id_kelas='" + cbx_idkelas.getSelectedItem()
                    + "',alamat='" + txt_alamat.getText()
                    + "',no_telp='" + txt_notelp.getText()
                    + "',id_spp='" + cbx_idspp.getSelectedItem()
                    + "' WHERE nisn='" + txt_nisn.getText() + "'";

            Connection conn = (Connection) koneksi.koneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.SUCCESS, Notification.Location.CENTER_RIGHT,
                    "Edit Succesfull");
            panel.showNotification();
        } catch (Exception e) {
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Edit Data"+ e);
            panel.showNotification();
        }
        tampilkandata();
        resetText();
    }

    public void delete_data() {
        hapustabel();

        try {
            String sql = "DELETE FROM tb_siswa WHERE nisn = '" + txt_nisn.getText() + "'";

            Connection conn = (Connection) koneksi.koneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.SUCCESS, Notification.Location.CENTER_RIGHT,
                    "Delete Succesfull");
            panel.showNotification();
        } catch (Exception e) {
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Delete Data"+ e);
            panel.showNotification();
        }
        tampilkandata();
        resetText();

    }

    public void search_data() {
        hapustabel();
        String key = txt_search.getText();
        try {
            Connection conn = (Connection) koneksi.koneksiDB();
            String sql = "Select tb_siswa.*, tb_kelas.id_kelas,komp_keahlian , tb_spp.id_spp,nominal from tb_siswa join tb_kelas "
                    + "on tb_kelas.id_kelas = tb_siswa.id_kelas join tb_spp on tb_spp.id_spp = tb_siswa.id_spp WHERE nama "
                    + "LIKE '%" + key + "%' OR nisn LIKE '%" + key + "%'";
            Statement stat = conn.createStatement();
            ResultSet set = stat.executeQuery(sql);
            while (set.next()) {
                String[] data = {set.getString("nisn"),
                    set.getString("nis"),
                    set.getString("nama"),
                    set.getString("id_kelas"),
                    set.getString("komp_keahlian"),
                    set.getString("alamat"),
                    set.getString("no_telp"),
                    set.getString("id_spp"),
                    set.getString("nominal")};
                tabmode.addRow(data);
            }

        } catch (Exception e) {
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Search Data"+ e);
            panel.showNotification();
        }
    }

    public void table_mouse_klik() {
        try {
            txt_nisn.setEditable(false);
            int row = Table.getSelectedRow();
            String table_klik = (Table.getModel().getValueAt(row, 0).toString());
            java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
            Statement stm = conn.createStatement();
            ResultSet sql = stm.executeQuery("Select tb_siswa.*, tb_kelas.id_kelas,komp_keahlian , tb_spp.id_spp,nominal from"
                    + " tb_siswa join tb_kelas on tb_kelas.id_kelas = tb_siswa.id_kelas join tb_spp on tb_spp.id_spp = tb_siswa.id_spp where nisn='" + table_klik + "'");
            if (sql.next()) {
                String add1 = sql.getString("nisn");
                txt_nisn.setText(add1);
                String add2 = sql.getString("nis");
                txt_nis.setText(add2);
                String add3 = sql.getString("nama");
                txt_nama.setText(add3);
                String add4 = sql.getString("id_kelas");
                cbx_idkelas.setSelectedItem(add4);
                String add5 = sql.getString("alamat");
                txt_alamat.setText(add5);
                String add6 = sql.getString("no_telp");
                txt_notelp.setText(add6);
                String add7 = sql.getString("id_spp");
                cbx_idspp.setSelectedItem(add7);
                String add8 = sql.getString("komp_keahlian");
                txt_komp_keahlian.setText(add8);
                String add9 = sql.getString("nominal");
                txt_nominal.setText(add9);
                
            }
        } catch (Exception e) {
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Mouse Click"+ e);
            panel.showNotification();
        }
    }
    
    public void model_cbx_idkelas(){
        try {
        Connection conn = (Connection)koneksi.koneksiDB();
        String sql = "Select id_kelas from tb_kelas";
        Statement stat = conn.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        while (rs.next()){
            cbx_idkelas.addItem(rs.getString("id_kelas"));
        }
        } catch (Exception e) {
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Cbx Id Kelas"+ e);
            panel.showNotification();
        }
        cbx_idkelas.setSelectedIndex(-1);
        txt_komp_keahlian.setText("");
        
    }
    public void model_cbx_idspp(){
        try {
        Connection conn = (Connection)koneksi.koneksiDB();
        String sql = "Select id_spp from tb_spp";
        Statement stat = conn.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        while (rs.next()){
            cbx_idspp.addItem(rs.getString("id_spp"));
        }
        } catch (Exception e) {
            Notification panel = new Notification(new Form_Menu_Admin(null), Notification.Type.WARNING, Notification.Location.CENTER_RIGHT,
                    "Ada Kesalahan Di Cbx Id Spp"+ e);
            panel.showNotification();
        }
        cbx_idspp.setSelectedIndex(-1);
        txt_nominal.setText("");
    }

}
